package org.tacografo.file.cardblockdriver;

public enum TipoDatos {
	//(tamaño(byte) min,tamaño(byte) max, valor por defecto)
		MF (""),
			EF_IC(""), // EF Archivo elemental
				CARDICCIDENTIFICATION(""),
					CLOCKSTOP("OCTET STRING"),
					CARDEXTENDEDSERIALNUMBER("ExtendedSerialNumber"),
					CARDAPPROVALNUMBER(" CardApprovalNumber"),
					CARDPERSONALISERID("OCTET STRING"),                                                                                                                                                                                                                   
					EMBEDDERICASSEMBLERID("OCTET STRING"),
					ICIDENTIFIER("OCTET STRING"),
			EF_ICC(""),
				CARDCHIPIDENTIFICATION(""),
					ICSERIALNUMBER("OCTET STRING"),
					ICMANUFACTURINGREFENCES("OCTET STRING"),
			DF_TACHOGRAPF(""),  //DF Archivo dedicado. Un DF puede contener otros archivos (EF o DF)
				EF_APPLICATION_IDENTIFICATION(""),
					DRIVERCARDAPPLICATIONIDENTIFICATION(""),
						TYPEOFTACHOGRAPHCARDID("EquipmentType"),
						CARDSTRUCTUREVERSION("CardStructureVersion"),
						NOOFEVENTSPERTYPE("NoOfEventsPerType"),
						NOOFFAULTSPERTYPE("NoOfFaultsPerType"),
						ACTIVITYSTRUCTURELENGTH("CardActivityLengthRange"),
						NOOFCARDVEHICLERECORDS("NoOfCardVehicleRecords"),
						NOOFCARDPLACERECORDS("NoOfCardPlaceRecords"),
				EF_CARD_CERTIFICATE(""),
					CARDCERTIFICATE("Certificate"),
				EF_CA_CERTIFICATE(""),
					MEMBERSTATECERTIFICATE("Certificate"),
				EF_IDENTIFICATION(""),
					CARDIDENTIFICATION(""),
						CARDISSUINGMEMBERSTATE("NationNumeric"),
						CARDNUMBER("CardNumber"),
						CARDISSUINGAUTORITYNAME("Name"),
						CARDISSUEDATE("TimeReal"),
						CARDVALIDITYBEGIN("TimeReal"),
						CARDEXPIRYDATE("TimeReal"),
					DRIVERCARDHOLDERIDENTIFICATION(""),
						CARDHOLDERNAME("HolderName"),
							HOLDERSURNAME("Name"),
							HOLDERFIRTSNAMES("Name"),
						CARDHOLDERBIRTHDATE("Datef"),
						CARDHOLDERPREFERREDLANGUAGE("Language"),
				EF_CARD_DOWNLOAD(""),
					LASTCARDDOWNLOAD("TimeReal"),
				EF_DRIVING_LICENSE_INFO(""),
					CARDDRIVINGLICENCEINFORMATION(""),
						DRIVINGLICENCEISSUINGAUTHORITY("Name"),
						DRIVINGLICENCEISSUINGNATION("NationNumeric"),
						DRIVINGLICENCENUMBER("IA5String"),
				EF_EVENTS_DATA(""),
					CARDEVENTDATA(""),
						CARDEVENTRECORDS("ArrayList<cardeventrecord>"),
							CARDEVENTRECORD(""),
								EVENTTYPE( "EventFaultType"),
								EVENTBEGINTIME("TimeReal"),
								EVENTENDTIME("TimeReal"),
								EVENTVEHICLEREGISTRATION("VehicleRegistrationIdentification"),
									VEHICLEREGISTRATIONNATION_CARDEVENTDATA("NationNumeric"),
									VEHICLEREGISTRATIONNUMBER_CARDEVENTDATA("VehicleRegistrationNumber"),
				EF_FAULTS_DATA(""),
					CARDFAULTDATA("ArrayList<cardFaultRecords>"),
						CARDFAULTRECORD(""),
							FAULTTYPE("EventFaultType"),
							FAULTBEGINTIME("TimeReal"),
							FAULTENDTIME("TimeReal"),
							FAULTVEHICLEREGISTRATION("VehicleRegistrationIdentification"),
								VEHICLEREGISTRATIONNATION_CARDFAULTDATA("NationNumeric"),
								VEHICLEREGISTRATIONNUMBER_CARDFAULTDATA("VehicleRegistrationNumber"),
				EF_DRIVER_ACTIVITY_DATA(""),
					CARDDRIVERACTIVITY(""),
						ACTIVITYPOINTEROLDESTADAYRECORD("INTEGER"),
						ACTIVITYPOINTERNEWESTRECORD("INTEGER"),
						ACTIVITYDAILYRECORDS("OCTET STRING"),
				EF_VEHICLES_USED(""),
					CARDVEHICLESUSED(""),
						VEHICLEPOINTERNEWESTRECORD("INTEGER"),
						CARDVEHICLERECORDS("ArrayList<CardVehicleRecord>"),
							CARDVEHICLERECORD(""),
								VEHICLEODOMETERBEGIN("OdometerShort"),
								VEHICLEODOMETEREND("OdometerShort"),
								VEHICLEFIRSTUSE("TimeReal"),
								VEHICLELASTUSE("TimeReal"),
								VEHICLEREGISTRATION("VehicleRegistrationIdentification"),
									VEHICLEREGISTRATIONNATION("NationNumeric"),
									VEHICLEREGISTRATIONNUMBER("VehicleRegistrationNumber"),
								VUDATABLOCKCOUNTER("VuDataBlockCounte"),	
				EF_PLACES(""),
					CARDPLACEDAILYWORKPERIOD(""),
						PLACEPOINTERNEWESTRECORD("INTEGER"),
						PLACERECORDS("ArrayList<PlaceRecord>"),
							PLACERECORD(""),
								ENTRYTIME("TimeReal"),
								ENTRYTYPEDAILYWORKPERIOD("EntryTypeDailyWorkPeriod"),
								DAILYWORKPERIODCOUNTRY("NationNumeric"),							
								DAILYWORKPERIODREGION("RegionNumeric"),
								VEHICLEODOMETERVALUE("OdometerShort"),							
				EF_CURRENT_USAGE(""),
					CARDCURRENTUSE(""),
						SESSIONOPENTIME("TimeReal"),
						SESSIONOPENVEHICLE("VehicleRegistrationIdentification"),
							VEHICLEREGISTRATIONNATION_CARDCURRENTUSE("NationNumeric"),
							VEHICLEREGISTRATIONNUMBER_CARDCURRENTUSE("VehicleRegistrationNumber"),
				EF_CONTROL_ACTIVITY_DATA(""),
					CARDCONTROLACTIVITYDATARECORD(""),
						CONTROLTYPE("ControlType"),
						CONTROLTIME("TimeRea"),
						CONTROLCARDNUMBER("FullCardNumber"),
							CARDTYPE("EquipmentType"),
							CARDISSUINGMEMBERSTATE_CONTROL("NationNumeric"),
							CARDNUMBER_CONTROL("CardNumber"),
						CONTROLVEHICLEREGISTRATION("VehicleRegistrationIdentification"),
							VEHICLEREGISTRATIONNATION_CONTROL("NationNumeric"),
							VEHICLEREGISTRATIONNUMBER_CONTROL("VehicleRegistrationNumber"),
						CONTROLDOWNLOADPERIODBEGIN("TimeReal"),
						CONTROLDOWNLOADPERIODEND("TimeReal"),
				EF_SPECIFIC_CONDITIONS(""),
					SPECIFICCONDITIONRECORD(""),
						ENTRYTIME_SPECIFIC("TimeReal"),
						SPECIFICCIONDITIONTYPE("SpecificConditionType");
		
		private String tipo;
		
		TipoDatos(String tipo){
			this.tipo=tipo;
		}
		
		public String getTipo(){
			return this.tipo;
		}
}
